spring:
  main:
    allow-circular-references: true
  application:
    name: LiVi
  datasource:
    # 配置数据库连接，允许批量查询
    url: jdbc:mysql://47.93.213.152:3307/livi?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 1qaz@WSX#EDC4rfv
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 47.93.213.152  # Redis服务器IP
      port: 6379           # Redis端口
      password: 1qaz@WSX#EDC4rfv  # Redis密码
      database: 0          # 默认数据库
  mail:
    host: smtp.qq.com
    port: 587
    username: haomarch7@qq.com
    # 密码是QQ邮箱的授权码，不是登录密码
    password: oprwrimlirdndcac
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

# 配置JWT的签名密钥(Base64编码March7)
jwt:
  sign-key: MDYxMU1hcmNodzc=
  # 过期时间，单位毫秒
  expire: 3600000
# 配置MyBatis-Plus
mybatis-plus:
  type-aliases-package: com.anxu.livi.pojo
  configuration:
    map-underscore-to-camel-case: true
#配置线程池（.yml 里用短横线，Java 里用驼峰，Spring 会自动映射）
thread-pool:
  core-size: 8          # 核心线程数
  max-size: 16          # 最大线程数
  queue-capacity: 50    # 任务队列容量
  keep-alive-time: 30   # 空闲线程存活时间（秒）
  pool-prefix-name: "async-task-"  # 线程名称前缀
#配置阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: smarthomeunity
    region: cn-beijing