spring:
  application:
    name: SmartHomeUnity
  datasource:
    url: jdbc:mysql://localhost:3306/smarthomeunity
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: haomarch7@qq.com
# 密码是QQ邮箱的授权码，不是登录密码
    password: oprwrimlirdndcac
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

# 配置JWT的签名密钥
jwt:
  sign-key: MDYxMU1hcmNodzc=

mybatis-plus:
  type-aliases-package: com.anxu.smarthomeunity.pojo
  configuration:
    map-underscore-to-camel-case: true
